image: proboci/ubuntu-16.04-lamp:php-7.2
steps:
  - name: Update Node and compile theme
    plugin: Script
    script: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      which nvm
      nvm install 10.16.3
      nvm alias default 10.16.3
      npm -v
      node -v
      cd $SRC_DIR/docroot/themes/siteden_surface
      npm ci
      npm run build
  - name: Build Drupal
    plugin: Script
    script: |
      composer self-update ; composer global update
      cd $SRC_DIR
      composer install --ansi
  - name: Run PhpUnit
    plugin: Script
    script:
      - cd $SRC_DIR/docroot/profiles/sitefarm_seed
      - $SRC_DIR/vendor/bin/phpunit --colors="always"
  - name: Drupal site setup
    plugin: Drupal
    drupalVersion: 8
    subDirectory: docroot
    runInstall: true
    profileName: sitefarm_seed
    installArgs: '--site-name="Testing SiteDen on Probo" --account-pass=probo'
  - name: Fix files directory permissions
    command: 'chown -R www-data:www-data /var/www/html/sites/default/files'
  - name: Run Behat NoJS
    plugin: Script
    script:
      - cd /var/www/html/profiles/sitefarm_seed
      - cp behat.probo.yml behat.yml
      - $SRC_DIR/vendor/bin/behat --profile probo --tags "~@javascript" --colors
  - name: Run Behat JS
    plugin: Script
    script:
      - apt-get update > /dev/null 2>&1
      - apt-get install google-chrome-stable xvfb -y > /dev/null 2>&1
      - wget http://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip > /dev/null 2>&1
      - sudo unzip chromedriver_linux64.zip -d /usr/bin
      - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar > /dev/null 2>&1
      - xvfb-run java -jar selenium-server-standalone-2.53.1.jar -Dwebdriver.chrome.driver="/usr/bin/chromedriver" > /dev/null 2>&1 & sleep 5
      - cd /var/www/html/profiles/sitefarm_seed
      - $SRC_DIR/vendor/bin/behat --profile probo --tags "@javascript" --colors --format progress
